import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useCreateCurrencyRate,useListCurrencyRates,useListCurrencies,getListCurrencyRatesQueryKey,getGetLatestCurrencyRateQueryKey } from "@workspace/api-client-react";
import { AccentButton,CrmDialog,DataTable,DateField,DangerIconButton,NumberField,OutlineButton,SelectField } from "@/components/crm";
import { formatDateTime } from "@/lib/format";
export function CurrencyDialog({open,onOpenChange}:{open:boolean;onOpenChange:(open:boolean)=>void}){
  const currencies=useListCurrencies(),rates=useListCurrencyRates(),create=useCreateCurrencyRate(),client=useQueryClient();
  const [currencyId,setCurrencyId]=useState(""),[rate,setRate]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10));
  const clear=()=>setRate("");
  const submit=()=>create.mutate({data:{currencyId:Number(currencyId),rate:Number(rate),rateDate:date}},{onSuccess:()=>{clear();client.invalidateQueries({queryKey:getListCurrencyRatesQueryKey()});client.invalidateQueries({queryKey:getGetLatestCurrencyRateQueryKey()})}});
  return <CrmDialog open={open} onOpenChange={onOpenChange} title="نرخی دراو" className="currency-dialog" footer={<OutlineButton onClick={()=>onOpenChange(false)}>داخستن</OutlineButton>}><div className="currency-form"><SelectField label="جۆری دراو" required value={currencyId} onChange={e=>setCurrencyId(e.target.value)}><option value="">جۆری دراو</option>{currencies.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</SelectField><NumberField label="نرخ" required value={rate} onChange={e=>setRate(e.target.value)}/><DateField label="بەروار" value={date} onChange={e=>setDate(e.target.value)}/><AccentButton icon="Add" disabled={!currencyId||!rate||create.isPending} onClick={submit}/><DangerIconButton icon="ChromeClose" onClick={clear}/></div><DataTable rows={rates.data??[]} loading={rates.isLoading} columns={[{key:"currencyName",header:"ناو",sortable:true},{key:"rate",header:"نرخ",sortable:true,align:"number"},{key:"recordedByName",header:"تۆمارکراوە لە لایەن",sortable:true},{key:"createdAt",header:"بەروار",sortable:true,render:r=>formatDateTime(r.createdAt)}]}/></CrmDialog>;
}