import { useState } from "react";
import { getGetItemPriceLookupQueryKey, getListItemsQueryKey, useGetItemPriceLookup, useListItems } from "@workspace/api-client-react";
import { AccentButton,ComboboxField,EmptyState,IconButton,Money,Qty } from "@/components/crm";
import { useUsdRate } from "@/hooks/use-usd-rate";
export function PriceLookupDrawer({open,onClose}:{open:boolean;onClose:()=>void}){
  const [itemId,setItemId]=useState(""),items=useListItems(undefined,{query:{queryKey:getListItemsQueryKey(),enabled:open}}),params={itemId:Number(itemId)||undefined},lookup=useGetItemPriceLookup(params,{query:{queryKey:getGetItemPriceLookupQueryKey(params),enabled:open&&!!itemId,retry:false}}),usd=useUsdRate();
  const data=lookup.data,prices=data?[["نرخی تاک",data.retailPrice],["نرخی کۆ",data.wholesalePrice],["نرخی تایبەت",data.specialPrice],["نرخی زیاتر",data.extraPrice]]:[] as [string,number][];
  if(!open)return null;
  return <div className="crm-drawer-overlay" onMouseDown={onClose}><aside className="shell-drawer price-drawer" onMouseDown={e=>e.stopPropagation()}><header><h3>نرخی کاڵاکان</h3><IconButton icon="ChromeClose" onClick={onClose}/></header><div className="shell-drawer-body"><label className="crm-field"><span>بارکۆد</span><select value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">گەڕان</option>{items.data?.map(i=><option key={i.id} value={i.id}>{i.barcode}</option>)}</select></label><ComboboxField label="ناوی کاڵا" value={data?.name??""} readOnly/><div className="crm-form-grid"><ComboboxField label="زنجیرە" readOnly/><ComboboxField label="سریاڵ نەمبەر" readOnly/></div><div className="price-cards">{prices.map(([title,value])=><div key={title}><strong>{title}</strong><Money value={value} currency="USD"/><Money value={Number(value)*Number(usd.rate??0)} currency="IQD"/></div>)}</div>{data?<table className="stock-table"><thead><tr><th>بڕی هەبوو</th><th>مەخزەن</th></tr></thead><tbody>{data.stock.map(stock=><tr key={stock.warehouseId}><td><Qty value={stock.quantity}/></td><td>{stock.warehouseName}</td></tr>)}</tbody></table>:<EmptyState/>}<AccentButton icon="Search" disabled={!itemId}>گەڕان</AccentButton></div></aside></div>;
}